export const data = [
  {
    id: 1,
    title: "Micro Api",
    text: "Micro Api is a specialized bank API developed to cater to the needs of clients, staff, and third-party organizations within the finance  sector. The project boasts a robust authentication system enhanced by JWT and tokens, ensuring secure access to its features. With a keen focus on data security, Micro Api implements usage limits to manage and control access, providing a seamless and controlled experience for users. Additionally, the project incorporates role-based authentication, enabling different levels of access and permissions based on user roles.",

    link: "https://github.com/ChrisOwuor/micro",
    img: "https://cdn-icons-png.flaticon.com/128/9346/9346304.png",
    stack: ["sqlite", "django", "django rest framework", "jwt"],
  },
  {
    id: 2,
    title: "Find me",
    text: "Find Me is a full-stack application designed to facilitate facial recognition between lost and found individuals. Leveraging deep learning models for facial recognition, the project adopts an MVC structure for efficient organization and separation of concerns. The application includes an API version, enabling seamless integration with third-party services and applications.This project represents a powerful solution for connecting lost individuals with their families or caretakers through cutting-edge technology ",
    link: "https://github.com/ChrisOwuor/Find-me/",
    img: "https://cdn-icons-png.flaticon.com/512/6819/6819113.png",
    stack: ["mysql", "django", "python", "javascript", "react", "Ai"],
  },
  {
    id: 3,
    title: "Mojo blog",
    text: "Mojo blog stands out as a comprehensive full-stack web application that goes beyond traditional blogging platforms. In addition to its captivating user interface built with React.js, Django, and Tailwind CSS, Mojo blog features advanced capabilities in blog content creation. The project integrates the OpenAI API for AI-driven blog generation, allowing for automated and intelligent content creation. Furthermore, the application seamlessly integrates with the Daraja API for M-Pesa, providing users with a complete and innovative experience that includes both AI-powered content generation and secure payment processing for subscriptions.",
    link: "https://github.com/ChrisOwuor/mojo-blog",
    img: "https://memberbenefits.com/wp-content/uploads/2023/04/cropped-icon_blue-circle-white-MB_201x201.webp",
    stack: ["React js", "Tailwind", "javascript", "django", "sqlite"],
  },
  {
    id: 4,
    title: " Express js Authentication",
    text: "I also developed a robust authentication system using Node.js, fortified by JSON Web Tokens (JWT) for secure user authentication, and seamlessly integrated it with a MongoDB database. To ensure the highest level of data security, I implemented the bcrypt package to encrypt user passwords before storing them. This comprehensive authentication solution not only guarantees the confidentiality of user information but also provides a smooth and efficient experience, allowing users to access the platform's features with confidence while maintaining the utmost privacy of their credentials.",
    link: "https://github.com/ChrisOwuor/authentication/tree/main",
    img: "https://cdn-icons-png.flaticon.com/512/753/753352.png",
    stack: ["mongodb", "express js", "jwt"],
  },
  {
    id: 5,
    title: "Kaybros Consulting limited",
    text: "I crafted a dynamic website for Kaybros Consulting Limited, designed to seamlessly bridge the gap between clients and the firm. Leveraging the power of React.js and the flexibility of Tailwind CSS, I built an engaging platform that not only showcases the comprehensive range of services offered by the company but also provides a user-friendly interface for clients to connect and explore testimonials.",
    link: "https://github.com/ChrisOwuor/kaybbros",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMIgpb4BqykvetUG0ufMVFEZj2E11_jnASJg&usqp=CAU",
    stack: ["React js", "Tailwind"],
  },
  {
    id: 6,
    title: "Furni",
    text: "Furni is an e-commerce project built with Django and MySQL. It utilizes Python for server-side logic and provides a seamless shopping experience for users. The technology stack ensures efficient data management and a secure platform for online transactions.",
    link: "https://github.com/ChrisOwuor/furni_e-commerce",
    img: "https://cdn-icons-png.flaticon.com/512/9203/9203620.png",
    stack: ["mysql", "django", "python"],
  },
];
